# #####################################################################
# Automatically generated by qmake (2.01a) Mon Oct 12 12:58:25 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .


QT += opengl \
    xml
CONFIG += qt \
    warn_on \
    thread \
    console \
    QGLViewer \
    OpenMesh \
    eigen3 \
    BertSharedLib \
    MacOSg++

EXT_DIR = ../extern
BERT_SHARED_DIR = ../shared

macx {
    CONFIG(debug, debug|release) {
        QMAKE_POST_LINK = dsymutil \"chemo.app/Contents/MacOS/chemo\"
    }
}

DEPENDPATH += $${BERT_SHARED_DIR}

include($${BERT_SHARED_DIR}/libs.pri)

INCLUDEPATH += . \
    $${BERT_SHARED_DIR} \
    $${EXT_DIR}

MOC_DIR = ./moc
OBJECTS_DIR = ./obj

QMAKE_CXXFLAGS += -Wall \
    -Wextra \
    -fPIC \
    -std=c++11

LIBS += -lGLU
#    -lpthread \
#    -lGLEW

# Input
SOURCES += main.cpp

OTHER_FILES += TODO.txt \
    data/shaders/picking.vert \
    data/shaders/picking.frag

HEADERS += \
    My_viewer.h \
    Atom.h \
    Core.h \
    Spatial_hash.h
