# #####################################################################
# Automatically generated by qmake (2.01a) Mon Oct 12 12:58:25 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .


QT += opengl \
    xml
CONFIG += qt \
    warn_on \
    thread \
    console \
    QGLViewer \
    OpenMesh \
    eigen3 \
    BertSharedLib  #\
#    MacOSg++

# to relink external libs used by the exetubale to copies inside of the bundle Contents/Frameworks dir
#    BUNDLE_DIR = chemo.app/Contents/
#    install_name_tool -change libboost_serialization.dylib @executable_path/../Frameworks/libboost_serialization.dylib $${BUNDLE_DIR}/MacOS/chemo

#CONFIG -= app_bundle

EXT_DIR = ../extern
BERT_SHARED_DIR = ../shared

DEPENDPATH += $${BERT_SHARED_DIR}

include($${BERT_SHARED_DIR}/libs.pri)

INCLUDEPATH += . \
    $${BERT_SHARED_DIR} \
    $${EXT_DIR}

MOC_DIR = ./moc
OBJECTS_DIR = ./obj

QMAKE_CXXFLAGS += -Wall \
    -Wextra \
    -fPIC \
    -std=c++11 \
    -stdlib=libc++

QMAKE_CXX = /opt/local/bin/clang++-mp-3.3
QMAKE_LINK = /opt/local/bin/clang++-mp-3.3

QMAKE_LFLAGS_X86_64 = $$QMAKE_CXXFLAGS

LIBS += -lGLU
#    -lpthread \
#    -lGLEW

# Input
SOURCES += main.cpp \
    RegularBspTree.cpp \
    Atom.cpp

OTHER_FILES += TODO.txt \
    data/shaders/picking.vert \
    data/shaders/picking.frag \
    data/shaders/force_calc.frag \
    data/shaders/force_calc.vert \
    README.txt \
    data/shaders/simple.vert \
    data/shaders/molecule.frag \
    data/shaders/fullscreen_square.vert \
    data/shaders/simple_texture.frag \
    data/shaders/temperature.vert \
    temperature.frag \
    data/shaders/temperature.frag \
    data/shaders/post.frag \
    data/shaders/blur_1D.frag \
    data/shaders/test.frag

HEADERS += \
    My_viewer.h \
    Atom.h \
    Core.h \
    Spatial_hash.h \
    Renderer.h \
    GPU_force.h \
    Atomic_force.h \
    RegularBspTree.h \
    Draggable.h \
    Level_elements.h \
    Visitor.h \
    Level_element_draw_visitor.h \
    Eigen_Matrix_serializer.h \
    State.h \
    End_condition.h \
    Level_data.h \
    Particle_system.h \
    unique_ptr_serialization.h \
    Sensor_data.h
